//------------------------------------------------------------------------------
// This code was generated by ResLoader. 
// Changes to this file may cause incorrect behaviour and will be lost if 
// the code is regenerated. 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Xml;
using System.IO;
using System.Text.RegularExpressions;

namespace ScoreCfg
{

    public class TScoreCfg : IResLoader
    {
        public const int MAX_Score_CFG_COUNT = 19;  // 最大数量
        
        public int Sum;  // 总和
        public int Score;  // 得分
        
        public int Load(ReadBuffer readBuffer, bool isSkip = false)
        {
            int ret = 0;
            
            
            ret = readBuffer.ReadInt32(ref Sum, isSkip); if(ret != 0) return ret;
            
            ret = readBuffer.ReadInt32(ref Score, isSkip); if(ret != 0) return ret;
            return 0;
        }
    }

    public class THeroCfgTab : IResLoader
    {
        public const int MAX_Score_CFG_COUNT = 19;  // 最大数量
        
        public int Count;
        public TScoreCfg[] TScoreCfg;
        
        public int Load(ReadBuffer readBuffer, bool isSkip = false)
        {
            int ret = 0;
            
            
            ret = readBuffer.ReadInt32(ref Count, isSkip); if(ret != 0) return ret;
            TScoreCfg = new TScoreCfg[Count];
            for (int j = 0; j < Count; ++j)
            {
                TScoreCfg[j] = new TScoreCfg();
                ret = TScoreCfg[j].Load(readBuffer, isSkip); if(ret != 0) return ret;
            }
            {
            
                TScoreCfg temp = new TScoreCfg();
                for(int j = Count; j < THeroCfgTab.MAX_Score_CFG_COUNT; ++j)
                {
                    ret = temp.Load(readBuffer, true); if(ret != 0) return ret;
                }
            }
            return 0;
        }
    }
    
}